---
all:
  children:
    keepalived:
      hosts:
        keepalived01:
          ansible_host: 10.1.1.253
          keepalived_node_ip: 10.1.1.253
          keepalived_node_priority: 150
        keepalived02:
          ansible_host: 10.1.1.252
          keepalived_node_ip: 10.1.1.252
          keepalived_node_priority: 140
        keepalived03:
          ansible_host: 10.1.1.251
          keepalived_node_ip: 10.1.1.251
          keepalived_node_priority: 130
      vars:
        ansible_user: osadmin
        ansible_become: true
